/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InternalRouteRouteImport } from './routes/_internal/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InternalWasteInfoRouteImport } from './routes/_internal/waste-info'
import { Route as InternalNotificationsRouteImport } from './routes/_internal/notifications'
import { Route as InternalHomeRouteImport } from './routes/_internal/home'
import { Route as InternalEnquiryRouteImport } from './routes/_internal/enquiry'
import { Route as InternalDataAnalyticsRouteImport } from './routes/_internal/data-analytics'
import { Route as InternalDashboardRouteImport } from './routes/_internal/dashboard'
import { Route as InternalConfigurationsIndexRouteImport } from './routes/_internal/configurations/index'
import { Route as InternalWasteDataRequestsRouteImport } from './routes/_internal/waste-data/requests'
import { Route as InternalWasteDataManagementRouteImport } from './routes/_internal/waste-data/management'
import { Route as InternalWasteDataApprovalRouteImport } from './routes/_internal/waste-data/approval'
import { Route as InternalUsersManagementRouteImport } from './routes/_internal/users/management'
import { Route as InternalUsersApprovalRouteImport } from './routes/_internal/users/approval'
import { Route as InternalSettingsEditProfileRouteImport } from './routes/_internal/settings/edit-profile'
import { Route as InternalSettingsChangePasswordRouteImport } from './routes/_internal/settings/change-password'
import { Route as InternalDataEntryStatisticRouteImport } from './routes/_internal/data-entry/statistic'
import { Route as InternalDataEntryNewFormRouteImport } from './routes/_internal/data-entry/new-form'
import { Route as InternalConfigurationsUtmPopulationRouteImport } from './routes/_internal/configurations/utm-population'
import { Route as InternalConfigurationsRolePermissionsRouteImport } from './routes/_internal/configurations/role-permissions'
import { Route as InternalConfigurationsNotificationEmailsRouteImport } from './routes/_internal/configurations/notification-emails'
import { Route as InternalConfigurationsLandfillingCostRouteImport } from './routes/_internal/configurations/landfilling-cost'
import { Route as InternalConfigurationsDisposalWasteRouteImport } from './routes/_internal/configurations/disposal-waste'
import { Route as InternalConfigurationsDepartmentsRouteImport } from './routes/_internal/configurations/departments'
import { Route as InternalDataEntryViewFormIndexRouteImport } from './routes/_internal/data-entry/view-form/index'
import { Route as InternalWasteDataRequestsRecordRouteImport } from './routes/_internal/waste-data/requests/record'
import { Route as InternalWasteDataManagementRecordRouteImport } from './routes/_internal/waste-data/management/record'
import { Route as InternalWasteDataApprovalRecordRouteImport } from './routes/_internal/waste-data/approval/record'
import { Route as InternalDataEntryViewFormRequestsRouteImport } from './routes/_internal/data-entry/view-form/requests'
import { Route as InternalDataEntryViewFormRecordRouteImport } from './routes/_internal/data-entry/view-form/record'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRouteRoute = InternalRouteRouteImport.update({
  id: '/_internal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalWasteInfoRoute = InternalWasteInfoRouteImport.update({
  id: '/waste-info',
  path: '/waste-info',
  getParentRoute: () => InternalRouteRoute,
} as any)
const InternalNotificationsRoute = InternalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => InternalRouteRoute,
} as any)
const InternalHomeRoute = InternalHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => InternalRouteRoute,
} as any)
const InternalEnquiryRoute = InternalEnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => InternalRouteRoute,
} as any)
const InternalDataAnalyticsRoute = InternalDataAnalyticsRouteImport.update({
  id: '/data-analytics',
  path: '/data-analytics',
  getParentRoute: () => InternalRouteRoute,
} as any)
const InternalDashboardRoute = InternalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InternalRouteRoute,
} as any)
const InternalConfigurationsIndexRoute =
  InternalConfigurationsIndexRouteImport.update({
    id: '/configurations/',
    path: '/configurations/',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalWasteDataRequestsRoute =
  InternalWasteDataRequestsRouteImport.update({
    id: '/waste-data/requests',
    path: '/waste-data/requests',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalWasteDataManagementRoute =
  InternalWasteDataManagementRouteImport.update({
    id: '/waste-data/management',
    path: '/waste-data/management',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalWasteDataApprovalRoute =
  InternalWasteDataApprovalRouteImport.update({
    id: '/waste-data/approval',
    path: '/waste-data/approval',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalUsersManagementRoute = InternalUsersManagementRouteImport.update({
  id: '/users/management',
  path: '/users/management',
  getParentRoute: () => InternalRouteRoute,
} as any)
const InternalUsersApprovalRoute = InternalUsersApprovalRouteImport.update({
  id: '/users/approval',
  path: '/users/approval',
  getParentRoute: () => InternalRouteRoute,
} as any)
const InternalSettingsEditProfileRoute =
  InternalSettingsEditProfileRouteImport.update({
    id: '/settings/edit-profile',
    path: '/settings/edit-profile',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalSettingsChangePasswordRoute =
  InternalSettingsChangePasswordRouteImport.update({
    id: '/settings/change-password',
    path: '/settings/change-password',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalDataEntryStatisticRoute =
  InternalDataEntryStatisticRouteImport.update({
    id: '/data-entry/statistic',
    path: '/data-entry/statistic',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalDataEntryNewFormRoute =
  InternalDataEntryNewFormRouteImport.update({
    id: '/data-entry/new-form',
    path: '/data-entry/new-form',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalConfigurationsUtmPopulationRoute =
  InternalConfigurationsUtmPopulationRouteImport.update({
    id: '/configurations/utm-population',
    path: '/configurations/utm-population',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalConfigurationsRolePermissionsRoute =
  InternalConfigurationsRolePermissionsRouteImport.update({
    id: '/configurations/role-permissions',
    path: '/configurations/role-permissions',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalConfigurationsNotificationEmailsRoute =
  InternalConfigurationsNotificationEmailsRouteImport.update({
    id: '/configurations/notification-emails',
    path: '/configurations/notification-emails',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalConfigurationsLandfillingCostRoute =
  InternalConfigurationsLandfillingCostRouteImport.update({
    id: '/configurations/landfilling-cost',
    path: '/configurations/landfilling-cost',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalConfigurationsDisposalWasteRoute =
  InternalConfigurationsDisposalWasteRouteImport.update({
    id: '/configurations/disposal-waste',
    path: '/configurations/disposal-waste',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalConfigurationsDepartmentsRoute =
  InternalConfigurationsDepartmentsRouteImport.update({
    id: '/configurations/departments',
    path: '/configurations/departments',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalDataEntryViewFormIndexRoute =
  InternalDataEntryViewFormIndexRouteImport.update({
    id: '/data-entry/view-form/',
    path: '/data-entry/view-form/',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalWasteDataRequestsRecordRoute =
  InternalWasteDataRequestsRecordRouteImport.update({
    id: '/record',
    path: '/record',
    getParentRoute: () => InternalWasteDataRequestsRoute,
  } as any)
const InternalWasteDataManagementRecordRoute =
  InternalWasteDataManagementRecordRouteImport.update({
    id: '/record',
    path: '/record',
    getParentRoute: () => InternalWasteDataManagementRoute,
  } as any)
const InternalWasteDataApprovalRecordRoute =
  InternalWasteDataApprovalRecordRouteImport.update({
    id: '/record',
    path: '/record',
    getParentRoute: () => InternalWasteDataApprovalRoute,
  } as any)
const InternalDataEntryViewFormRequestsRoute =
  InternalDataEntryViewFormRequestsRouteImport.update({
    id: '/data-entry/view-form/requests',
    path: '/data-entry/view-form/requests',
    getParentRoute: () => InternalRouteRoute,
  } as any)
const InternalDataEntryViewFormRecordRoute =
  InternalDataEntryViewFormRecordRouteImport.update({
    id: '/data-entry/view-form/record',
    path: '/data-entry/view-form/record',
    getParentRoute: () => InternalRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof InternalDashboardRoute
  '/data-analytics': typeof InternalDataAnalyticsRoute
  '/enquiry': typeof InternalEnquiryRoute
  '/home': typeof InternalHomeRoute
  '/notifications': typeof InternalNotificationsRoute
  '/waste-info': typeof InternalWasteInfoRoute
  '/configurations/departments': typeof InternalConfigurationsDepartmentsRoute
  '/configurations/disposal-waste': typeof InternalConfigurationsDisposalWasteRoute
  '/configurations/landfilling-cost': typeof InternalConfigurationsLandfillingCostRoute
  '/configurations/notification-emails': typeof InternalConfigurationsNotificationEmailsRoute
  '/configurations/role-permissions': typeof InternalConfigurationsRolePermissionsRoute
  '/configurations/utm-population': typeof InternalConfigurationsUtmPopulationRoute
  '/data-entry/new-form': typeof InternalDataEntryNewFormRoute
  '/data-entry/statistic': typeof InternalDataEntryStatisticRoute
  '/settings/change-password': typeof InternalSettingsChangePasswordRoute
  '/settings/edit-profile': typeof InternalSettingsEditProfileRoute
  '/users/approval': typeof InternalUsersApprovalRoute
  '/users/management': typeof InternalUsersManagementRoute
  '/waste-data/approval': typeof InternalWasteDataApprovalRouteWithChildren
  '/waste-data/management': typeof InternalWasteDataManagementRouteWithChildren
  '/waste-data/requests': typeof InternalWasteDataRequestsRouteWithChildren
  '/configurations/': typeof InternalConfigurationsIndexRoute
  '/data-entry/view-form/record': typeof InternalDataEntryViewFormRecordRoute
  '/data-entry/view-form/requests': typeof InternalDataEntryViewFormRequestsRoute
  '/waste-data/approval/record': typeof InternalWasteDataApprovalRecordRoute
  '/waste-data/management/record': typeof InternalWasteDataManagementRecordRoute
  '/waste-data/requests/record': typeof InternalWasteDataRequestsRecordRoute
  '/data-entry/view-form/': typeof InternalDataEntryViewFormIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof InternalDashboardRoute
  '/data-analytics': typeof InternalDataAnalyticsRoute
  '/enquiry': typeof InternalEnquiryRoute
  '/home': typeof InternalHomeRoute
  '/notifications': typeof InternalNotificationsRoute
  '/waste-info': typeof InternalWasteInfoRoute
  '/configurations/departments': typeof InternalConfigurationsDepartmentsRoute
  '/configurations/disposal-waste': typeof InternalConfigurationsDisposalWasteRoute
  '/configurations/landfilling-cost': typeof InternalConfigurationsLandfillingCostRoute
  '/configurations/notification-emails': typeof InternalConfigurationsNotificationEmailsRoute
  '/configurations/role-permissions': typeof InternalConfigurationsRolePermissionsRoute
  '/configurations/utm-population': typeof InternalConfigurationsUtmPopulationRoute
  '/data-entry/new-form': typeof InternalDataEntryNewFormRoute
  '/data-entry/statistic': typeof InternalDataEntryStatisticRoute
  '/settings/change-password': typeof InternalSettingsChangePasswordRoute
  '/settings/edit-profile': typeof InternalSettingsEditProfileRoute
  '/users/approval': typeof InternalUsersApprovalRoute
  '/users/management': typeof InternalUsersManagementRoute
  '/waste-data/approval': typeof InternalWasteDataApprovalRouteWithChildren
  '/waste-data/management': typeof InternalWasteDataManagementRouteWithChildren
  '/waste-data/requests': typeof InternalWasteDataRequestsRouteWithChildren
  '/configurations': typeof InternalConfigurationsIndexRoute
  '/data-entry/view-form/record': typeof InternalDataEntryViewFormRecordRoute
  '/data-entry/view-form/requests': typeof InternalDataEntryViewFormRequestsRoute
  '/waste-data/approval/record': typeof InternalWasteDataApprovalRecordRoute
  '/waste-data/management/record': typeof InternalWasteDataManagementRecordRoute
  '/waste-data/requests/record': typeof InternalWasteDataRequestsRecordRoute
  '/data-entry/view-form': typeof InternalDataEntryViewFormIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_internal': typeof InternalRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_internal/dashboard': typeof InternalDashboardRoute
  '/_internal/data-analytics': typeof InternalDataAnalyticsRoute
  '/_internal/enquiry': typeof InternalEnquiryRoute
  '/_internal/home': typeof InternalHomeRoute
  '/_internal/notifications': typeof InternalNotificationsRoute
  '/_internal/waste-info': typeof InternalWasteInfoRoute
  '/_internal/configurations/departments': typeof InternalConfigurationsDepartmentsRoute
  '/_internal/configurations/disposal-waste': typeof InternalConfigurationsDisposalWasteRoute
  '/_internal/configurations/landfilling-cost': typeof InternalConfigurationsLandfillingCostRoute
  '/_internal/configurations/notification-emails': typeof InternalConfigurationsNotificationEmailsRoute
  '/_internal/configurations/role-permissions': typeof InternalConfigurationsRolePermissionsRoute
  '/_internal/configurations/utm-population': typeof InternalConfigurationsUtmPopulationRoute
  '/_internal/data-entry/new-form': typeof InternalDataEntryNewFormRoute
  '/_internal/data-entry/statistic': typeof InternalDataEntryStatisticRoute
  '/_internal/settings/change-password': typeof InternalSettingsChangePasswordRoute
  '/_internal/settings/edit-profile': typeof InternalSettingsEditProfileRoute
  '/_internal/users/approval': typeof InternalUsersApprovalRoute
  '/_internal/users/management': typeof InternalUsersManagementRoute
  '/_internal/waste-data/approval': typeof InternalWasteDataApprovalRouteWithChildren
  '/_internal/waste-data/management': typeof InternalWasteDataManagementRouteWithChildren
  '/_internal/waste-data/requests': typeof InternalWasteDataRequestsRouteWithChildren
  '/_internal/configurations/': typeof InternalConfigurationsIndexRoute
  '/_internal/data-entry/view-form/record': typeof InternalDataEntryViewFormRecordRoute
  '/_internal/data-entry/view-form/requests': typeof InternalDataEntryViewFormRequestsRoute
  '/_internal/waste-data/approval/record': typeof InternalWasteDataApprovalRecordRoute
  '/_internal/waste-data/management/record': typeof InternalWasteDataManagementRecordRoute
  '/_internal/waste-data/requests/record': typeof InternalWasteDataRequestsRecordRoute
  '/_internal/data-entry/view-form/': typeof InternalDataEntryViewFormIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/data-analytics'
    | '/enquiry'
    | '/home'
    | '/notifications'
    | '/waste-info'
    | '/configurations/departments'
    | '/configurations/disposal-waste'
    | '/configurations/landfilling-cost'
    | '/configurations/notification-emails'
    | '/configurations/role-permissions'
    | '/configurations/utm-population'
    | '/data-entry/new-form'
    | '/data-entry/statistic'
    | '/settings/change-password'
    | '/settings/edit-profile'
    | '/users/approval'
    | '/users/management'
    | '/waste-data/approval'
    | '/waste-data/management'
    | '/waste-data/requests'
    | '/configurations/'
    | '/data-entry/view-form/record'
    | '/data-entry/view-form/requests'
    | '/waste-data/approval/record'
    | '/waste-data/management/record'
    | '/waste-data/requests/record'
    | '/data-entry/view-form/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/data-analytics'
    | '/enquiry'
    | '/home'
    | '/notifications'
    | '/waste-info'
    | '/configurations/departments'
    | '/configurations/disposal-waste'
    | '/configurations/landfilling-cost'
    | '/configurations/notification-emails'
    | '/configurations/role-permissions'
    | '/configurations/utm-population'
    | '/data-entry/new-form'
    | '/data-entry/statistic'
    | '/settings/change-password'
    | '/settings/edit-profile'
    | '/users/approval'
    | '/users/management'
    | '/waste-data/approval'
    | '/waste-data/management'
    | '/waste-data/requests'
    | '/configurations'
    | '/data-entry/view-form/record'
    | '/data-entry/view-form/requests'
    | '/waste-data/approval/record'
    | '/waste-data/management/record'
    | '/waste-data/requests/record'
    | '/data-entry/view-form'
  id:
    | '__root__'
    | '/'
    | '/_internal'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_internal/dashboard'
    | '/_internal/data-analytics'
    | '/_internal/enquiry'
    | '/_internal/home'
    | '/_internal/notifications'
    | '/_internal/waste-info'
    | '/_internal/configurations/departments'
    | '/_internal/configurations/disposal-waste'
    | '/_internal/configurations/landfilling-cost'
    | '/_internal/configurations/notification-emails'
    | '/_internal/configurations/role-permissions'
    | '/_internal/configurations/utm-population'
    | '/_internal/data-entry/new-form'
    | '/_internal/data-entry/statistic'
    | '/_internal/settings/change-password'
    | '/_internal/settings/edit-profile'
    | '/_internal/users/approval'
    | '/_internal/users/management'
    | '/_internal/waste-data/approval'
    | '/_internal/waste-data/management'
    | '/_internal/waste-data/requests'
    | '/_internal/configurations/'
    | '/_internal/data-entry/view-form/record'
    | '/_internal/data-entry/view-form/requests'
    | '/_internal/waste-data/approval/record'
    | '/_internal/waste-data/management/record'
    | '/_internal/waste-data/requests/record'
    | '/_internal/data-entry/view-form/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InternalRouteRoute: typeof InternalRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internal': {
      id: '/_internal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof InternalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internal/waste-info': {
      id: '/_internal/waste-info'
      path: '/waste-info'
      fullPath: '/waste-info'
      preLoaderRoute: typeof InternalWasteInfoRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/notifications': {
      id: '/_internal/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof InternalNotificationsRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/home': {
      id: '/_internal/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof InternalHomeRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/enquiry': {
      id: '/_internal/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof InternalEnquiryRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/data-analytics': {
      id: '/_internal/data-analytics'
      path: '/data-analytics'
      fullPath: '/data-analytics'
      preLoaderRoute: typeof InternalDataAnalyticsRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/dashboard': {
      id: '/_internal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof InternalDashboardRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/configurations/': {
      id: '/_internal/configurations/'
      path: '/configurations'
      fullPath: '/configurations/'
      preLoaderRoute: typeof InternalConfigurationsIndexRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/waste-data/requests': {
      id: '/_internal/waste-data/requests'
      path: '/waste-data/requests'
      fullPath: '/waste-data/requests'
      preLoaderRoute: typeof InternalWasteDataRequestsRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/waste-data/management': {
      id: '/_internal/waste-data/management'
      path: '/waste-data/management'
      fullPath: '/waste-data/management'
      preLoaderRoute: typeof InternalWasteDataManagementRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/waste-data/approval': {
      id: '/_internal/waste-data/approval'
      path: '/waste-data/approval'
      fullPath: '/waste-data/approval'
      preLoaderRoute: typeof InternalWasteDataApprovalRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/users/management': {
      id: '/_internal/users/management'
      path: '/users/management'
      fullPath: '/users/management'
      preLoaderRoute: typeof InternalUsersManagementRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/users/approval': {
      id: '/_internal/users/approval'
      path: '/users/approval'
      fullPath: '/users/approval'
      preLoaderRoute: typeof InternalUsersApprovalRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/settings/edit-profile': {
      id: '/_internal/settings/edit-profile'
      path: '/settings/edit-profile'
      fullPath: '/settings/edit-profile'
      preLoaderRoute: typeof InternalSettingsEditProfileRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/settings/change-password': {
      id: '/_internal/settings/change-password'
      path: '/settings/change-password'
      fullPath: '/settings/change-password'
      preLoaderRoute: typeof InternalSettingsChangePasswordRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/data-entry/statistic': {
      id: '/_internal/data-entry/statistic'
      path: '/data-entry/statistic'
      fullPath: '/data-entry/statistic'
      preLoaderRoute: typeof InternalDataEntryStatisticRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/data-entry/new-form': {
      id: '/_internal/data-entry/new-form'
      path: '/data-entry/new-form'
      fullPath: '/data-entry/new-form'
      preLoaderRoute: typeof InternalDataEntryNewFormRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/configurations/utm-population': {
      id: '/_internal/configurations/utm-population'
      path: '/configurations/utm-population'
      fullPath: '/configurations/utm-population'
      preLoaderRoute: typeof InternalConfigurationsUtmPopulationRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/configurations/role-permissions': {
      id: '/_internal/configurations/role-permissions'
      path: '/configurations/role-permissions'
      fullPath: '/configurations/role-permissions'
      preLoaderRoute: typeof InternalConfigurationsRolePermissionsRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/configurations/notification-emails': {
      id: '/_internal/configurations/notification-emails'
      path: '/configurations/notification-emails'
      fullPath: '/configurations/notification-emails'
      preLoaderRoute: typeof InternalConfigurationsNotificationEmailsRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/configurations/landfilling-cost': {
      id: '/_internal/configurations/landfilling-cost'
      path: '/configurations/landfilling-cost'
      fullPath: '/configurations/landfilling-cost'
      preLoaderRoute: typeof InternalConfigurationsLandfillingCostRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/configurations/disposal-waste': {
      id: '/_internal/configurations/disposal-waste'
      path: '/configurations/disposal-waste'
      fullPath: '/configurations/disposal-waste'
      preLoaderRoute: typeof InternalConfigurationsDisposalWasteRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/configurations/departments': {
      id: '/_internal/configurations/departments'
      path: '/configurations/departments'
      fullPath: '/configurations/departments'
      preLoaderRoute: typeof InternalConfigurationsDepartmentsRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/data-entry/view-form/': {
      id: '/_internal/data-entry/view-form/'
      path: '/data-entry/view-form'
      fullPath: '/data-entry/view-form/'
      preLoaderRoute: typeof InternalDataEntryViewFormIndexRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/waste-data/requests/record': {
      id: '/_internal/waste-data/requests/record'
      path: '/record'
      fullPath: '/waste-data/requests/record'
      preLoaderRoute: typeof InternalWasteDataRequestsRecordRouteImport
      parentRoute: typeof InternalWasteDataRequestsRoute
    }
    '/_internal/waste-data/management/record': {
      id: '/_internal/waste-data/management/record'
      path: '/record'
      fullPath: '/waste-data/management/record'
      preLoaderRoute: typeof InternalWasteDataManagementRecordRouteImport
      parentRoute: typeof InternalWasteDataManagementRoute
    }
    '/_internal/waste-data/approval/record': {
      id: '/_internal/waste-data/approval/record'
      path: '/record'
      fullPath: '/waste-data/approval/record'
      preLoaderRoute: typeof InternalWasteDataApprovalRecordRouteImport
      parentRoute: typeof InternalWasteDataApprovalRoute
    }
    '/_internal/data-entry/view-form/requests': {
      id: '/_internal/data-entry/view-form/requests'
      path: '/data-entry/view-form/requests'
      fullPath: '/data-entry/view-form/requests'
      preLoaderRoute: typeof InternalDataEntryViewFormRequestsRouteImport
      parentRoute: typeof InternalRouteRoute
    }
    '/_internal/data-entry/view-form/record': {
      id: '/_internal/data-entry/view-form/record'
      path: '/data-entry/view-form/record'
      fullPath: '/data-entry/view-form/record'
      preLoaderRoute: typeof InternalDataEntryViewFormRecordRouteImport
      parentRoute: typeof InternalRouteRoute
    }
  }
}

interface InternalWasteDataApprovalRouteChildren {
  InternalWasteDataApprovalRecordRoute: typeof InternalWasteDataApprovalRecordRoute
}

const InternalWasteDataApprovalRouteChildren: InternalWasteDataApprovalRouteChildren =
  {
    InternalWasteDataApprovalRecordRoute: InternalWasteDataApprovalRecordRoute,
  }

const InternalWasteDataApprovalRouteWithChildren =
  InternalWasteDataApprovalRoute._addFileChildren(
    InternalWasteDataApprovalRouteChildren,
  )

interface InternalWasteDataManagementRouteChildren {
  InternalWasteDataManagementRecordRoute: typeof InternalWasteDataManagementRecordRoute
}

const InternalWasteDataManagementRouteChildren: InternalWasteDataManagementRouteChildren =
  {
    InternalWasteDataManagementRecordRoute:
      InternalWasteDataManagementRecordRoute,
  }

const InternalWasteDataManagementRouteWithChildren =
  InternalWasteDataManagementRoute._addFileChildren(
    InternalWasteDataManagementRouteChildren,
  )

interface InternalWasteDataRequestsRouteChildren {
  InternalWasteDataRequestsRecordRoute: typeof InternalWasteDataRequestsRecordRoute
}

const InternalWasteDataRequestsRouteChildren: InternalWasteDataRequestsRouteChildren =
  {
    InternalWasteDataRequestsRecordRoute: InternalWasteDataRequestsRecordRoute,
  }

const InternalWasteDataRequestsRouteWithChildren =
  InternalWasteDataRequestsRoute._addFileChildren(
    InternalWasteDataRequestsRouteChildren,
  )

interface InternalRouteRouteChildren {
  InternalDashboardRoute: typeof InternalDashboardRoute
  InternalDataAnalyticsRoute: typeof InternalDataAnalyticsRoute
  InternalEnquiryRoute: typeof InternalEnquiryRoute
  InternalHomeRoute: typeof InternalHomeRoute
  InternalNotificationsRoute: typeof InternalNotificationsRoute
  InternalWasteInfoRoute: typeof InternalWasteInfoRoute
  InternalConfigurationsDepartmentsRoute: typeof InternalConfigurationsDepartmentsRoute
  InternalConfigurationsDisposalWasteRoute: typeof InternalConfigurationsDisposalWasteRoute
  InternalConfigurationsLandfillingCostRoute: typeof InternalConfigurationsLandfillingCostRoute
  InternalConfigurationsNotificationEmailsRoute: typeof InternalConfigurationsNotificationEmailsRoute
  InternalConfigurationsRolePermissionsRoute: typeof InternalConfigurationsRolePermissionsRoute
  InternalConfigurationsUtmPopulationRoute: typeof InternalConfigurationsUtmPopulationRoute
  InternalDataEntryNewFormRoute: typeof InternalDataEntryNewFormRoute
  InternalDataEntryStatisticRoute: typeof InternalDataEntryStatisticRoute
  InternalSettingsChangePasswordRoute: typeof InternalSettingsChangePasswordRoute
  InternalSettingsEditProfileRoute: typeof InternalSettingsEditProfileRoute
  InternalUsersApprovalRoute: typeof InternalUsersApprovalRoute
  InternalUsersManagementRoute: typeof InternalUsersManagementRoute
  InternalWasteDataApprovalRoute: typeof InternalWasteDataApprovalRouteWithChildren
  InternalWasteDataManagementRoute: typeof InternalWasteDataManagementRouteWithChildren
  InternalWasteDataRequestsRoute: typeof InternalWasteDataRequestsRouteWithChildren
  InternalConfigurationsIndexRoute: typeof InternalConfigurationsIndexRoute
  InternalDataEntryViewFormRecordRoute: typeof InternalDataEntryViewFormRecordRoute
  InternalDataEntryViewFormRequestsRoute: typeof InternalDataEntryViewFormRequestsRoute
  InternalDataEntryViewFormIndexRoute: typeof InternalDataEntryViewFormIndexRoute
}

const InternalRouteRouteChildren: InternalRouteRouteChildren = {
  InternalDashboardRoute: InternalDashboardRoute,
  InternalDataAnalyticsRoute: InternalDataAnalyticsRoute,
  InternalEnquiryRoute: InternalEnquiryRoute,
  InternalHomeRoute: InternalHomeRoute,
  InternalNotificationsRoute: InternalNotificationsRoute,
  InternalWasteInfoRoute: InternalWasteInfoRoute,
  InternalConfigurationsDepartmentsRoute:
    InternalConfigurationsDepartmentsRoute,
  InternalConfigurationsDisposalWasteRoute:
    InternalConfigurationsDisposalWasteRoute,
  InternalConfigurationsLandfillingCostRoute:
    InternalConfigurationsLandfillingCostRoute,
  InternalConfigurationsNotificationEmailsRoute:
    InternalConfigurationsNotificationEmailsRoute,
  InternalConfigurationsRolePermissionsRoute:
    InternalConfigurationsRolePermissionsRoute,
  InternalConfigurationsUtmPopulationRoute:
    InternalConfigurationsUtmPopulationRoute,
  InternalDataEntryNewFormRoute: InternalDataEntryNewFormRoute,
  InternalDataEntryStatisticRoute: InternalDataEntryStatisticRoute,
  InternalSettingsChangePasswordRoute: InternalSettingsChangePasswordRoute,
  InternalSettingsEditProfileRoute: InternalSettingsEditProfileRoute,
  InternalUsersApprovalRoute: InternalUsersApprovalRoute,
  InternalUsersManagementRoute: InternalUsersManagementRoute,
  InternalWasteDataApprovalRoute: InternalWasteDataApprovalRouteWithChildren,
  InternalWasteDataManagementRoute:
    InternalWasteDataManagementRouteWithChildren,
  InternalWasteDataRequestsRoute: InternalWasteDataRequestsRouteWithChildren,
  InternalConfigurationsIndexRoute: InternalConfigurationsIndexRoute,
  InternalDataEntryViewFormRecordRoute: InternalDataEntryViewFormRecordRoute,
  InternalDataEntryViewFormRequestsRoute:
    InternalDataEntryViewFormRequestsRoute,
  InternalDataEntryViewFormIndexRoute: InternalDataEntryViewFormIndexRoute,
}

const InternalRouteRouteWithChildren = InternalRouteRoute._addFileChildren(
  InternalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InternalRouteRoute: InternalRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
